apiVersion: v1
kind: Service
metadata:
  name: mi-frontend-service
spec:
  type: NodePort
  selector:
    app: mi-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  
