apiVersion: v1
kind: Service
metadata:
  name: mi-backend-index-service
spec:
  type: NodePort
  selector:
    app: mi-backend-index
  ports:
    - protocol: TCP
      port: 80 #puerto en el que espera el ingress
      targetPort: 5000 #puerto que escucha el dockerfile/servidor
