#apiVersion: v1
#kind: Service
#metadata:
#  name: mi-ingress-service
#  namespace: ingress-nginx
#spec:
 # type: LoadBalancer
 # selector:
  #  app.kubernetes.io/name: ingress-nginx
   # app.kubernetes.io/component: controller
 # ports:
  #  - name: http
   #   protocol: TCP
    #  port: 80
     # targetPort: http
    #- name: https
     # protocol: TCP
     # port: 443
     # targetPort: https


